version: 40
properties:
- name: alex_repo_relpath
  value: alexandria/gc-alexandria
  archived: false
jobs:
- name: Github Push
  steps:
  - !PushRepository
    name: gc-alexandria
    remoteUrl: https://github.com/ShadowySupercode/gc-alexandria
    passwordSecret: github_access_token
    force: false
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Container Image
  steps:
  - !CheckoutStep
    name: code checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !BuildImageStep
    name: build & push image
    dockerfile: Dockerfile
    output: !RegistryOutput
      tags: '@server@/@property:alex_repo_relpath@/alexandria:@build_number@ @server@/@property:alex_repo_relpath@/alexandria:@commit_hash@'
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
